#############################################################################
# Makefile for building: qdownloader
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? 18. ??? 13:19:09 2012
# Project:  qdownloader.pro
# Template: subdirs
# Command: c:\qtsdk\desktop\qt\4.7.4\mingw\bin\qmake.exe -spec c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\win32-g++ CONFIG+=release -o Makefile qdownloader.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\qtsdk\desktop\qt\4.7.4\mingw\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-src

src\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) e:\work\Qt\magnetic\qdownloader2\src\src.pro -spec c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) e:\work\Qt\magnetic\qdownloader2\src\src.pro -spec c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-src: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) first
sub-src-all: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: qdownloader.pro  c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/win32-g++/qmake.conf c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/qconfig.pri \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/modules/qt_webkit_version.pri \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/qt_functions.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/qt_config.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/exclusive_builds.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/default_pre.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/win32/default_pre.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/release.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/debug_and_release.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/default_post.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/win32/default_post.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/win32/thread.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/qt.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/moc.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/warn_on.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/win32/rtti.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/win32/exceptions.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/win32/stl.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/shared.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/win32/windows.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/resources.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/uic.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/yacc.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/lex.prf \
		c:/QtSDK/Desktop/Qt/4.7.4/mingw/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\win32-g++ CONFIG+=release -o Makefile qdownloader.pro
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\qconfig.pri:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\modules\qt_webkit_version.pri:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\qt_functions.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\qt_config.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\exclusive_builds.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\default_pre.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\win32\default_pre.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\release.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\debug_and_release.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\default_post.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\win32\default_post.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\win32\thread.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\qt.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\moc.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\warn_on.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\win32\rtti.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\win32\exceptions.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\win32\stl.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\shared.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\win32\windows.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\resources.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\uic.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\yacc.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\lex.prf:
c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec c:\QtSDK\Desktop\Qt\4.7.4\mingw\mkspecs\win32-g++ CONFIG+=release -o Makefile qdownloader.pro

qmake_all: sub-src-qmake_all FORCE

make_default: sub-src-make_default FORCE
make_first: sub-src-make_first FORCE
all: sub-src-all FORCE
clean: sub-src-clean FORCE
distclean: sub-src-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets FORCE

sub-src-sub_Debug: src\$(MAKEFILE)
	cd src\ && $(MAKE) debug
debug: sub-src-sub_Debug

sub-src-sub_Release: src\$(MAKEFILE)
	cd src\ && $(MAKE) release
release: sub-src-sub_Release

sub-src-check: src\$(MAKEFILE)
	cd src\ && $(MAKE) check
check: sub-src-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

